name: AWS

on:
  schedule:
    - cron: '30 21 * * *'   # Runs at 03:00 AM IST
  workflow_dispatch: # Allows manual triggering
  
jobs:
  php-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

    - name: Run PHP script on EC2
      env:
        AWS_HOST: ${{ secrets.AWS_HOST }}
        AWS_USER: ${{ secrets.AWS_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $AWS_USER@$AWS_HOST 'bash -s' << 'EOF'
        # Ensure the necessary directories and permissions
        mkdir -p ~/my-repo
        cd ~/my-repo

        # Remove any existing clone
        rm -rf repo

        # Clone the repository
        git clone https://github.com/SimperTVGuide/SimperTVGuide repo
        cd repo

        # Run the PHP script
        php tempest.php --epg config=tempest.config.xml invgz
        rm tempest_config/epg/simper_epg_original.xml
        rm tempest_config/epg/simper_epg.xml
        EOF
    
    - name: Pull latest
      run: |
        git pull
    
    - name: Commit updated epg.xml
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated EPG
