name: dns

on:
  schedule:
    - cron: '30 0 * * *'   # Runs at 06:00 AM IST
  workflow_dispatch: # Allows manual triggering
  
jobs:
  php-script:
    runs-on: ubuntu-latest

    steps:
    - name: Set up custom DNS resolver
      run: |
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf > /dev/null
        
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Git identity
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        
    - name: Execute Script
      run: |
        php tempest.php --epg config=jio.config.xml invgz
        rm tempest_config/epg/jio_epg_original.xml
        rm tempest_config/epg/jio_epg.xml
        git add .
        git commit -m "Automated commit"
        git push
