name: Gio_EPG_Grabber

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *" # every day at 08:00 AM IST

jobs:
  epg:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests xmltodict pysocks
          pip install pytz
      - name: Get EPG Data
        run: python epg.py epg.xml.gz
   
      - name: Move epg.xml.gz to another folder
        run: mv epg.xml.gz tempest_config/epg/epg.xml.gz
      - name: pull latest
        run: |
          git pull
      - name: Commit updated epg.xml.gz
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated EPG