name: openvpn

on:
  schedule:
    - cron: '30 0 * * *'   # Runs at 06:00 AM IST
  workflow_dispatch: # Allows manual triggering
  
jobs:
  php-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up OpenVPN
      env:
        VPN_CONFIG: ${{ secrets.VPN_CONFIG }}
        VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
        VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
      run: |
        # Decode and save the VPN configuration file
        echo $VPN_CONFIG | base64 --decode > vpn-config.ovpn
    
        # Create a file for VPN credentials
        echo -e "$VPN_USERNAME\n$VPN_PASSWORD" > vpn-credentials.txt

        # Update the VPN config to use the credentials file
        echo "auth-user-pass vpn-credentials.txt" >> vpn-config.ovpn

        # Install OpenVPN
        sudo apt-get update
        sudo apt-get install -y openvpn

        # Start OpenVPN in the background
        sudo openvpn --config vpn-config.ovpn --daemon

        # Wait for OpenVPN to establish connection
        sleep 15

    - name: Verify VPN Connection
      run: |
        curl ifconfig.me
    
    - name: Set up Git identity
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        
    - name: Execute Script
      run: |
        php tempest.php --epg config=jio.config.xml invgz
        rm tempest_config/epg/jio_epg_original.xml
        rm tempest_config/epg/jio_epg.xml
    
    - name: Pull latest
      run: |
        git pull
        
    - name: Commit updated epg.xml
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated EPG
