name: Run PHP script with proxy

on:
  schedule:
    - cron: '30 0 * * *'   # Runs at 06:00 AM IST
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Set up Git identity
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    
    - name: Install dependencies
      run: pip install requests
      
    - name: Fetch proxy
      id: fetch_proxy
      run: |
        python get_proxy.py
        echo "::set-output name=proxy::$(cat proxy.txt)"  # Assuming the proxy is saved in proxy.txt
      
    - name: Run PHP script with proxy
      run: php tempest.php --epg config=jio.config.xml invgz ${{ steps.fetch_proxy.outputs.proxy }}
      
    - name: pull latest
      run: |
        git pull
      # Commit all changed files back to the repository

    - name: Commit updated epg.xml
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated EPG  
