name: PushEPG

on:
  workflow_run:
    workflows: ["EPGPython", "EPGShell"]
    types:
      - completed   
  workflow_dispatch:
  
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.Push_File }}
      with:
        source_file: 'epg/'
        destination_repo: 'simperpie/simperpie.github.io'
        destination_folder: 'TVGuie'
        user_email: '91105635+simperpie@users.noreply.github.com'
        user_name: 'simperpie'
        commit_message: 'Automated EPG'
