name: push_tempest_epg

on:
  workflow_run:
    workflows: ["tempest_epg"]
    types:
      - completed   
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        path: source_repo

    - name: Checkout destination repository
      uses: actions/checkout@v4
      with:
        repository: simperpie/simperpie.github.io
        path: destination_repo
        token: ${{ secrets.Push_File }}

    - name: Copy files
      run: |
        cp -r source_repo/tempest_config/epg/* simperpie.github.io/epg/

    - name: Commit and push changes
      run: |
        cd destination_repo
        git config --global user.email "91105635+simperpie@users.noreply.github.com"
        git config --global user.name "simperpie"
        git add .
        git commit -m "Automated EPG update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.Push_File }}
