name: PushEPG

on:
  workflow_run:
    workflows: ["EPGPython", "EPGShell"]
    types:
      - completed   
  workflow_dispatch:
  
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.Push_File }}
      run: |
        find epg/ -type f -exec cp {} /tmp/ \; # Copy all files within epg directory to /tmp
        cd /tmp/
        git clone --single-branch --branch main ***github.com/simperpie/simperpie.github.io.git destination-repo # Clone destination repo
        cd destination-repo
        mkdir -p TVGuide
        cp -R /tmp/* TVGuide/ # Copy all files from /tmp to TVGuide folder in destination repo
        git add .
        git commit -m 'Automated EPG'
        git push
