name: PushEPG

on:
  workflow_run:
    workflows: ["EPGPython", "EPGShell"]
    types:
      - completed   
  workflow_dispatch:
  
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare destination repository
      run: |
        git clone https://x-access-token:${{ secrets.Push_File }}@github.com/simperpie/simperpie.github.io.git
        mkdir -p simperpie.github.io/TVGuide
    - name: Copy files
      run: cp -R tempest_config/epg/* simperpie.github.io/TVGuide

    - name: Commit and push changes
      run: |
        cd simperpie.github.io
        git config user.name "simperpie"
        git config user.email "91105635+simperpie@users.noreply.github.com"
        git add TVGuide
        git commit -m "Automated EPG"
        git push
