name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PUSH_TOKEN_FROM_PRIVATE_TO_MY_PAGE }}
      with:
        source_file: 'tempest_config/epg/tvguide.xml.gz'
        destination_repo: 'simperpie/simperpie.github.io'
        destination_folder: 'tvguide'
        user_email: '91105635+simperpie@users.noreply.github.com'
        user_name: 'simperpie'
        commit_message: 'Automated update'
