name: PushEPG

on:
  workflow_run:
    workflows: ["EPGPython", "EPGShell"]
    types:
      - completed   
  workflow_dispatch:
  
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configure Git
      run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      with:
        source_file: 'epg/*'
        destination_repo: 'simperpie/s0ndeep.github.io'
        destination_folder: '.'
        commit_message: 'Automated EPG'
