name: PushEPG

on:
  workflow_run:
    workflows: ["EPGPython", "EPGShell"]
    types:
      - completed
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to temporary directory
        run: |
          find epg/ -type f -exec cp {} /tmp/ \; # Copy all files within epg directory to /tmp

      - name: Clone destination repository
        run: |
          cd /tmp/
          git clone --single-branch --branch main ***github.com/simperpie/simperpie.github.io.git destination-repo

      - name: Copy files to destination repository
        run: |
          cd /tmp/destination-repo
          mkdir -p TVGuide
          cp -R /tmp/* TVGuide/ # Copy all files from /tmp to TVGuide folder in destination repo

      - name: Commit and push changes
        run: |
          cd /tmp/destination-repo
          git config user.email "91105635+simperpie@users.noreply.github.com"
          git config user.name "simperpie"
          git add .
          git commit -m 'Automated EPG'
          git push
