name: PushEPG

on:
  workflow_run:
    workflows: ["EPGPython", "EPGShell"]
    types:
      - completed   
  workflow_dispatch:
  
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Pushes test file
      run: |
        cp -r epg/* .
        git add .
        git config --local user.email "91105635+simperpie@users.noreply.github.com"
        git config --local user.name "simperpie"
        git commit -m "Automated EPG"
        git push https://simperpie:${{ secrets.Push_File }}@github.com/simperpie/simperpie.github.io HEAD:TVGuide
      shell: bash
