name: push_epg

on:
  workflow_run:
    workflows: ["tempest_epg", "zio_epg"]
    types:
      - completed   
  workflow_dispatch:
  
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare destination repository
      run: |
        git clone https://x-access-token:${{ secrets.Push_File }}@github.com/simperpie/simperpie.github.io.git
        mkdir -p simperpie.github.io/epg
    - name: Copy files
      run: cp -R tempest_config/epg/* simperpie.github.io/epg

    - name: Commit and push changes
      run: |
        cd simperpie.github.io
        git config user.name "simperpie"
        git config user.email "91105635+simperpie@users.noreply.github.com"
        git add epg
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Automated EPG"
          git push
        fi
