name: Share File

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: config
      run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

    - name: Copy file to temp location
      run: cp tempest_config/epg/tvguide.xml.gz /tmp/shared_file
      
    - name: Add file
      run: |
        git add .

    - name: Commit changes
      run: |
        git commit -m "Update shared file"
      
    - name: Push changes to public repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PUBLIC_REPO_TOKEN }}
        branch: main  # Adjust branch name as needed
        repository: simperpie/updates  # Replace username/public-repo with your public repository's path
