name: Share File

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Copy file to public repo
      run: |
        cp tempest_config/epg/tvguide.xml.gz simperpie/update
        cd simperpie/update
        git config --local user.email "you@example.com"
        git config --local user.name "Your Name"
        git add important.txt
        git commit -m "Update shared file"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
