name: Add Sensitive Files and Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Remote Repository
      uses: actions/checkout@v2
      with:
        repository: simperpie/tvguide # Replace with the owner and repository name
        ref: main # Replace with the branch name

    - name: Add Sensitive Files
      run: |
        # Copy the sensitive file from the current repository to the checked out repository
        cp tempest_config/epg/tvguide.xml.gz $GITHUB_WORKSPACE/simperpie/update/tvguide.xml.gz
        
    - name: Commit Changes
      run: |
        cd $GITHUB_WORKSPACE/repo_path
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Add sensitive file"
        
    - name: Push Changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        # Execute your build process here
