name: Push tvguide.xml.gz to Update Repo

on:
  push:
    branches:
      - main  # adjust as needed

jobs:
  push_file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout tempest repository
      uses: actions/checkout@v2
      with:
        repository: simperpie/tempest
        token: ${{ secrets.PUBLIC_REPO_TOKEN }}

    - name: Move to tempest_config/epg directory
      run: cd tempest_config/epg

    - name: Copy tvguide.xml.gz to public repo
      run: |
        cp tvguide.xml.gz ../update

    - name: Commit and push changes
      run: |
        cd ../update
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add tvguide.xml.gz
        git commit -m "Update tvguide.xml.gz from tempest repository"
        git push origin main  # adjust the branch name as needed
