name: Share File

on:
  push:
    branches:
      - main  # adjust as needed

jobs:
  push_file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout private repository
      uses: actions/checkout@v2
      with:
        repository: simperpie/tempest
        token: ${{ secrets.PUBLIC_REPO_TOKEN }}
    
    - name: Copy file to public repo
      run: |
        cp tempest_config/epg/tvguide.xml.gz update/
        # You might need to add additional setup here depending on your file structure
    
    - name: Commit and push changes
      run: |
        cd path/to/public/repo
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add .
        git commit -m "Update file from private repo"
        git push origin main  # adjust the branch name as needed
