name: Simper TV Guide

on:
  schedule:
    - cron: '30 21 * * *'   # Runs at 03:00 AM IST
  workflow_dispatch: # Allows manual triggering
  
jobs:
  php-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Git identity
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        
    - name: Execute Script
      run: |
        php tempest.php --epg config=tempest.config.xml invgz
        rm tempest_config/epg/simper_epg_original.xml
        rm tempest_config/epg/simper_epg.xml
    
    - name: Pull latest
      run: |
        git pull
    
    - name: Commit updated epg.xml
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated EPG